zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    estoqueservice: /estoque/**
    pedidoservice: /pedido/**

hystrix:
  command:
    estoqueservice:
      execution.isolation.thread.timeoutInMilliseconds: 2500
    pedidoservice:
      execution.isolation.thread.timeoutInMilliseconds: 3000

estoqueservice:
  ribbon:
    ReadTimeout: 8000